version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: supervisor-redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    networks:
      - supervisor-network

  app:
    build: .
    container_name: supervisor-app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
      - /var/www/vendor
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/database/database.sqlite
    depends_on:
      - redis
    networks:
      - supervisor-network
    restart: unless-stopped

volumes:
  redis_data:

networks:
  supervisor-network:
    driver: bridge
