services:
  redis:
    image: redis:7-alpine
    container_name: laravel-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - laravel-network

  app:
    build: .
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./storage/app/files:/var/www/html/storage/app/files
    depends_on:
      - redis
    networks:
      - laravel-network

  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel-network

  # Worker para todas as filas, priorizando high-priority
  queue-high:
    build: .
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    command: php artisan queue:work redis --queue=high-priority,default,low-priority --sleep=1 --tries=3 --max-time=3600
    depends_on:
      - redis
      - app
    networks:
      - laravel-network
    deploy:
      replicas: 2

  # Worker para default e low-priority
  queue-default:
    build: .
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    command: php artisan queue:work redis --queue=default,low-priority --sleep=2 --tries=3 --max-time=3600
    depends_on:
      - redis
      - app
    networks:
      - laravel-network
    deploy:
      replicas: 2

  # Worker apenas para low-priority
  queue-low:
    build: .
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    command: php artisan queue:work redis --queue=low-priority --sleep=3 --tries=3 --max-time=3600
    depends_on:
      - redis
      - app
    networks:
      - laravel-network
    deploy:
      replicas: 1

volumes:
  redis_data:
    driver: local

networks:
  laravel-network:
    driver: bridge