version: '3.8'

services:
  app:
    build: .
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./storage/app/files:/var/www/html/storage/app/files
    depends_on:
      - redis
    networks:
      - laravel-network

  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel-network

  redis:
    image: redis:7-alpine
    container_name: laravel-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - laravel-network

  # Worker para fila de alta prioridade
  queue-high:
    build: .
    container_name: queue-high-worker
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    command: php artisan queue:work redis --queue=high --sleep=3 --tries=3 --max-time=3600
    depends_on:
      - redis
      - app
    networks:
      - laravel-network
    deploy:
      replicas: 3

  # Worker para fila padrão
  queue-default:
    build: .
    container_name: queue-default-worker
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    command: php artisan queue:work redis --queue=default --sleep=3 --tries=3 --max-time=3600
    depends_on:
      - redis
      - app
    networks:
      - laravel-network
    deploy:
      replicas: 2

  # Worker para fila de baixa prioridade
  queue-low:
    build: .
    container_name: queue-low-worker
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    command: php artisan queue:work redis --queue=low --sleep=5 --tries=3 --max-time=3600
    depends_on:
      - redis
      - app
    networks:
      - laravel-network

  # Monitor de filas
  queue-monitor:
    build: .
    container_name: queue-monitor
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    command: php artisan queue:monitor redis --queue=high,default,low
    depends_on:
      - redis
      - app
    networks:
      - laravel-network

volumes:
  redis_data:
    driver: local

networks:
  laravel-network:
    driver: bridge